Repository comfy-lang/comfy, pull requests merged in 2025-07, with the labels that each got.

#4 feat: compile hello world example
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  src/generator.rs
  src/main.rs
  src/parser.rs
  src/syscalls.rs
  src/tokenizer.rs
  src/utils.rs
  tests/hello_world.fy
Labels: enhancement

#5 chore: update readme
  README.md
Labels: documentation

#6 feat: code generator call refactor
  .gitignore
  src/generator.rs
  src/main.rs
Labels: enhancement

#9 fix: order of syscalls in readme.md
  README.md
Labels: documentation

#10 feat: support variable declarations and identifiers in syscall wrappers
  src/generator.rs
  src/main.rs
  src/parser.rs
  src/syscalls.rs
  src/tokenizer.rs
  tests/hello_world.fy
Labels: enhancement

#11 feat: make variable names unique to function
  src/generator.rs
  src/parser.rs
  src/utils.rs
  tests/hello_world.fy
Labels: enhancement

#13 chore: add logo
  README.md
  assets/comfylang.png
Labels: documentation

#17 Feat: read syscall & co ^~^ 🌸💕🌙
  README.md
  src/generator.rs
  src/parser.rs
  src/syscalls.rs
  src/tokenizer.rs
  src/utils.rs
  tests/read_return_test.fy
  tests/read_test.fy
  util/host-run.sh
  util/link_compile.sh
Labels: enhancement

#23 feat(ci): check build on core branches
  .github/workflows/build.yml
Labels: enhancement

#21 Dev into main ,,, it's time
  .github/workflows/build.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  assets/comfylang.png
  project.comfx
  src/backend/arm32/asm.rs
  src/backend/arm32/mod.rs
  src/backend/arm32/section.rs
  src/backend/arm32/syscall_mapper.rs
  src/backend/generator.rs
  src/backend/mod.rs
  src/backend/syscalls.rs
  src/extra/config.rs
  src/extra/mod.rs
  src/extra/utils.rs
  src/frontend/mod.rs
  src/frontend/parser.rs
  src/frontend/tokenizer.rs
  src/generator.rs
  src/main.rs
  src/syscalls.rs
  src/utils.rs
  tests/hello_world.fy
  tests/open_test.fy
  tests/read_return_test.fy
  tests/read_test.fy
  util/host-run.sh
  util/link_compile.sh
Labels: enhancement

#93 Feat: Preprocessor
  README.md
  examples/hello_world.fy
  examples/inline_asm_test.fy
  examples/open_test.fy
  examples/preprocessor/src/info.md
  examples/preprocessor/src/main.fy
  examples/preprocessor/src/test/local_import.fy
  examples/read_return_test.fy
  examples/read_test.fy
  examples/sysinfo_return_test.fy
  examples/sysinfo_test.fy
  project.comfx
  src/extra/config.rs
  src/frontend/mod.rs
  src/frontend/preprocessor.rs
  src/main.rs
Labels: enhancement

#96 Bug: Added config fallback
  src/extra/config.rs
Labels: bug

#92 feat(#26): explicit types
  README.md
  examples/immutable_buffers.fy
  examples/read_return_test.fy
  examples/static_types_spectest.fy
  examples/static_types_test.fy
  examples/type_sys_test.fy
  examples/typed_syscalls.fy
  src/backend/arm32/asm.rs
  src/backend/arm32/section.rs
  src/backend/generator.rs
  src/backend/syscalls.rs
  src/extra/utils.rs
  src/frontend/parser.rs
  src/frontend/tokenizer.rs
  src/main.rs
Labels: enhancement

#98 feat: comment support
  examples/comments.fy
  src/frontend/tokenizer.rs
Labels: enhancement
